### ISSUE TITLE
Darbots Shared Lib TO-DO List

### ISSUE THREAD

**Issue by ToiletCommander** [DarlingtonProgramming/FTC-DarBots-Rover-Ruckus#2]
We haven't made a schedule yet for the exact development date. But keep tuned and hopefully they will all be done before the summer vacation ends!

---

- [x] Motor Controller
    - [x] Motor Controller Code
    - [ ] Motor Contorller Test
- [x] Motion Contorller
    - [x] Motion Controller Code & RobotWheel Code
    - [ ] Motion Controller Test
- [ ] ServoUsingMotor Controller
    - [x] ServoUsingMotor Code
    - [ ] ServoUsingMotor_WithLimitSwitch Code
    - [ ] ServoUsingMotor Test
- [ ] Chasis Programming
    - [x] Chassis Basic Control Class
    - [x] Omniwheel Chassis Code
    - [ ] Mechanum Chassis Code
    - [ ] Omniwheel Chassis Test
    - [ ] Mechanum Chassis Test
